# Generated by Django 2.2.1 on 2019-09-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190911_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('person', models.ManyToManyField(to='app01.Person')),
            ],
            options={
                'db_table': 'teacher',
                'verbose_name_plural': '教师',
                'verbose_name': '教师',
            },
        ),
    ]
